-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS rooms(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    visibility int2 NOT NULL DEFAULT 2, -- VISIBILITY_PRIVATE
    room_title VARCHAR(64) NOT NULL,
    room_description VARCHAR(512),
    room_dates DATE ARRAY,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT now()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE rooms CASCADE;
-- +goose StatementEnd
