-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS events(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    visibility int2 NOT NULL DEFAULT(2),-- VISIBILITY_PRIVATE
    event_title VARCHAR(128) NOT NULL,
    event_description VARCHAR(512),
    event_start TIMESTAMP,
    event_end TIMESTAMP,
    event_created_at TIMESTAMP DEFAULT now()
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE events CASCADE;
-- +goose StatementEnd
