-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (
        START WITH 100_000
        MINVALUE 100_000
        INCREMENT BY 1
        ) PRIMARY KEY,

    username VARCHAR(64) UNIQUE NOT NULL,
    first_name VARCHAR(64) NOT NULL,
    last_name VARCHAR(64),
    password VARCHAR(64) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX idx_users_username;
DROP TABLE users CASCADE;
-- +goose StatementEnd
